---
version: "3.3"

services:
  database:
    image: 'mongo:4.2.2'
    ports:
      - '27017:27017'

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
